services:
  #SERVICE DISCOVERY
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service-container
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 5

  #SERVICE CONFIG
  config-service:
    build: ./config-service
    container_name: config-service-container
    ports:
      - "9999:9999"
    expose:
      - "9999"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 5
    depends_on:
      discovery-service:
        condition: service_healthy

  #SERVICE CUSTOMER
  customer-service:
    build: ./customer-service
    container_name: customer-service-container
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy

  #SERVICE ACCOUNT
  account-service:
    build: ./account-service
    container_name: account-service-container
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 5
    depends_on:
      customer-service:
        condition: service_healthy

  #SERVICE GATEWAY
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service-container
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      account-service:
        condition: service_healthy



